// Copyright (c) 2025 Leon Lee

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace AbyssTags
{
	/**
	 * 用与角色类型数据注册表中指定角色类型
	 */
	namespace CharacterClass
	{
		namespace Hero
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Elementalist);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Assassin);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ranger);
		}

		namespace Enemy
		{
			namespace Minions
			{
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Elementalist);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Assassin);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ranger);
			}

			namespace Boss
			{
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Elementalist);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Assassin);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ranger);
			}
		}
	}

	
	namespace SetByCaller
	{
		namespace DamageType
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Physical);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fire);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ice);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lightning);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Poison);
		}

		namespace Debuff
		{
			//Debuff类型
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Physical);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fire);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ice);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lightning);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Poison);
			
			//Debuff的数值属性
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chance);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Duration);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frequency);
		}
	}
	
	/**
	 * 技能标签
	 */
	namespace Ability
	{
		namespace Melee
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SwordLightAttack);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SwordHeavyAttack);
		}

		namespace Projectile
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(FireBalt);
		}

		namespace Beam
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Electrocute);
		}
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateOnGiven);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Death);
		
		namespace Enemy
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack);
		}
	}
	
	/**
	 * 技能冷却标签
	 */
	namespace Cooldown
	{
		namespace Melee
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SwordLightAttack);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SwordHeavyAttack);
		}

		namespace Projectile
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(FireBalt);
		}
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivateOnGiven);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Death);
		
		namespace Enemy
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack);
		}
	}

	namespace Events
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KillScored);
		
		namespace Montage
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(FireBolt);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ElectrocuteBeam);
		}
		namespace Enemy
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeleeTraceHit);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact);
		}
		
	}

	namespace Block
	{
		namespace Input
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityPressed);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityHeld);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityReleased);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jump);
		}
	}

	namespace Status
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dead);
	}
	
	/**
	 * Attributes
	 */
	namespace Attributes
	{
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Health);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxHealth);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mana);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxMana);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxStamina);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PhysicalPower);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicPower);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Defense);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CritRate);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CritDamage);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(BlockChance);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicPenetration);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PhysicalPenetration);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackSpeed);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveSpeed);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CooldownReduction);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PhysicalResistance);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MagicResistance);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillPoints);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(TalentPoints);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillSlotAmount);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CurrentXP);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(XPMultiplier);
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(IncomingDamage);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(IncomingXP);
	}

	/**
	 * 输入标签，用于记录可以输入映射的按键
	 */
	namespace InputTag
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(LMB);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(RMB);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Shift);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Ctrl);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Alt);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Super);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(A);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(B);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(C);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(D);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(E);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(F);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(G);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(H);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(I);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(J);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(K);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(M);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(N);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(O);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(P);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(S);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(T);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(U);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(V);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(W);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(X);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Y);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Z);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(num1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(num2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(num3);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(num4);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(num5);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(num6);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(num7);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(num8);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(num9);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(num0);

	}
	
	/**
	 * 
	 */
	namespace GlobalData
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(GlobalData);
		
		
	}
}


