// Copyright Epic Games, Inc. All Rights Reserved.
// Finished.
#pragma once


#if COMMONUSER_OSSV1

// Online Subsystem (OSS v1) includes and forward declares
// 在线子系统（OSS 版本 1）包含并预先声明了
#include "OnlineSubsystemTypes.h"
class IOnlineSubsystem;
struct FOnlineError;
using FOnlineErrorType = FOnlineError;
using ELoginStatusType = ELoginStatus::Type;

#else

// Online Services (OSS v2) includes and forward declares
// 在线服务（OSS v2）包含并预先声明了
#include "Online/Connectivity.h"
#include "Online/OnlineError.h"
namespace UE::Online
{
	enum class ELoginStatus : uint8;
	enum class EPrivilegeResults : uint32;
	enum class EUserPrivileges : uint8;
	using IAuthPtr = TSharedPtr<class IAuth>;
	using IOnlineServicesPtr = TSharedPtr<class IOnlineServices>;
	template <typename OpType>
	class TOnlineResult;
	struct FAuthLogin;
	struct FConnectionStatusChanged;
	struct FExternalUIShowLoginUI;
	struct FAuthLoginStatusChanged;
	struct FQueryUserPrivilege;
	struct FAccountInfo;
}
using FOnlineErrorType = UE::Online::FOnlineError;
using ELoginStatusType = UE::Online::ELoginStatus;

#endif

#include "CommonUserTypes.generated.h"


/** Enum specifying where and how to run online queries */
/** 用于指定在线查询的运行位置及方式的枚举类型 */
UENUM(BlueprintType)
enum class ECommonUserOnlineContext : uint8
{
	/** Called from game code, this uses the default system but with special handling that could merge results from multiple contexts */
	/** 由游戏代码调用，此函数使用默认系统，但会进行特殊处理，以便将来自多个环境的结果进行合并 */
	Game,

	/** The default engine online system, this will always exist and will be the same as either Service or Platform */
	/** 默认的在线引擎系统，此系统始终存在，并且与“服务”或“平台”系统相同 */
	Default,
	
	/** Explicitly ask for the external service, which may not exist */
	/** 明确要求使用外部服务，但该服务可能并不存在 */
	Service,

	/** Looks for external service first, then falls back to default */
	/** 首先查找外部服务，若未找到则回退至默认设置 */
	ServiceOrDefault,
	
	/** Explicitly ask for the platform system, which may not exist */
	/** 明确要求获取平台系统信息，但该系统可能并不存在 */
	Platform,

	/** Looks for platform system first, then falls back to default */
	/** 首先查找平台系统，若未找到则转而使用默认设置 */
	PlatformOrDefault,

	/** Invalid system */
	/** 无效系统 */

	Invalid
};

/** Enum describing the state of initialization for a specific user */
/** 描述特定用户初始化状态的枚举 */
UENUM(BlueprintType)
enum class ECommonUserInitializationState : uint8
{
	/** User has not started login process */
	/** 用户尚未开始登录流程 */
	Unknown,

	/** Player is in the process of acquiring a user id with local login */
	/** 玩家正在通过本地登录的方式获取用户 ID */
	DoingInitialLogin,

	/** Player is performing the network login, they have already logged in locally */
	/** 玩家正在进行网络登录操作，他们已经在本地完成了登录 */
	DoingNetworkLogin,

	/** Player failed to log in at all */
	/** 玩家完全无法登录 */
	FailedtoLogin,

	
	/** Player is logged in and has access to online functionality */
	/** 玩家已登录并拥有使用在线功能的权限 */
	LoggedInOnline,

	/** Player is logged in locally (either guest or real user), but cannot perform online actions */
	/** 玩家已在本地登录（可能是访客用户，也可能是真实用户），但无法执行在线操作 */
	LoggedInLocalOnly,


	/** Invalid state or user */
	/** 无效状态或用户 */
	Invalid,
};

/** Enum specifying different privileges and capabilities available to a user */
/** 定义了用户可享有的不同权限和功能的枚举 */
UENUM(BlueprintType)
enum class ECommonUserPrivilege : uint8
{
	/** Whether the user can play at all, online or offline */
	/** 用户是否能够进行游戏操作（无论是在线还是离线状态） */
	CanPlay,

	/** Whether the user can play in online modes */
	/** 用户是否能够在在线模式下进行游戏 */
	CanPlayOnline,

	/** Whether the user can use text chat */
	/** 用户是否可以使用文字聊天 */
	CanCommunicateViaTextOnline,

	/** Whether the user can use voice chat */
	/** 用户是否可以使用语音聊天功能 */
	CanCommunicateViaVoiceOnline,

	/** Whether the user can access content generated by other users */
	/** 用户是否能够访问其他用户生成的内容 */
	CanUseUserGeneratedContent,

	/** Whether the user can ever participate in cross-play */
	/** 用户是否能够参与跨平台游戏活动 */
	CanUseCrossPlay,

	/** Invalid privilege (also the count of valid ones) */
	/** 无效权限（以及有效权限的数量） */
	Invalid_Count					UMETA(Hidden)
};

/** Enum specifying the general availability of a feature or privilege, this combines information from multiple sources */
/** 该枚举用于指定一项功能或权限的总体可用性，它整合了来自多个来源的信息 */
UENUM(BlueprintType)
enum class ECommonUserAvailability : uint8
{
	/** State is completely unknown and needs to be queried */
	/** 状态完全未知，需要进行查询 */
	Unknown,

	/** This feature is fully available for use right now */
	/** 该功能目前可完全正常使用 */
	NowAvailable,

	/** This might be available after the completion of normal login procedures */
	/** 这项功能可能在完成常规登录流程后才会可用 */
	PossiblyAvailable,

	/** This feature is not available now because of something like network connectivity but may be available in the future */
	/** 目前此功能无法使用，可能是由于网络连接等原因所致，但未来可能会恢复可用。 */
	CurrentlyUnavailable,

	/** This feature will never be available for the rest of this session due to hard account or platform restrictions */
	/** 由于账户或平台的严格限制，此功能在本次会话结束后将无法再使用 */
	AlwaysUnavailable,

	/** Invalid feature */
	/** 无效特性 */
	Invalid,
};

/** Enum giving specific reasons why a user may or may not use a certain privilege */
/** 一个枚举类型，用于说明用户可能或可能不会使用某项特权的具体原因 */
UENUM(BlueprintType)
enum class ECommonUserPrivilegeResult : uint8
{
	/** State is unknown and needs to be queried */
	/** 状态未知，需要进行查询 */
	Unknown,

	/** This privilege is fully available for use */
	/** 此权限可完全自由使用 */
	Available,

	/** User has not fully logged in */
	/** 用户尚未完成登录 */
	UserNotLoggedIn,

	/** User does not own the game or content */
	/** 用户并不拥有该游戏或相关内容 */
	LicenseInvalid,

	/** The game needs to be updated or patched before this will be available */
	/** 在此功能可用之前，游戏需要进行更新或补丁操作 */
	VersionOutdated,

	/** No network connection, this may be resolved by reconnecting */
	/** 没有网络连接，这种情况可能通过重新连接来解决 */
	NetworkConnectionUnavailable,

	/** Parental control failure */
	/** 父母控制失败 */
	AgeRestricted,

	/** Account does not have a required subscription or account type */
	/** 账户未拥有必需的订阅服务或账户类型 */
	AccountTypeRestricted,

	/** Another account/user restriction such as being banned by the service */
	/** 另一种账户/用户限制，例如因违反服务规定而被封禁 */
	AccountUseRestricted,

	/** Other platform-specific failure */
	/** 其他平台特定的故障 */
	PlatformFailure,
};

/** Used to track the progress of different asynchronous operations */
/** 用于记录不同异步操作的执行进度 */
enum class ECommonUserAsyncTaskState : uint8
{
	/** The task has not been started */
	/** 该任务尚未开始执行 */
	NotStarted,
	/** The task is currently being processed */
	/** 当前任务正在处理中 */
	InProgress,
	/** The task has completed successfully */
	/** 该任务已成功完成 */
	Done,
	/** The task failed to complete */
	/** 该任务未能完成 */
	Failed
};

/** Detailed information about the online error. Effectively a wrapper for FOnlineError. */
/** 关于在线错误的详细信息。实际上是对 FOnlineError 的一种封装。*/
USTRUCT(BlueprintType)
struct FOnlineResultInformation
{
	GENERATED_BODY()

	/** Whether the operation was successful or not. If it was successful, the error fields of this struct will not contain extra information. */
	/** 表示操作是否成功。如果操作成功，则此结构体中的错误字段将不包含任何额外信息。*/
	UPROPERTY(BlueprintReadOnly)
	bool bWasSuccessful = true;

	/** The unique error id. Can be used to compare against specific handled errors. */
	/** 该唯一的错误标识符。可用于与已处理的特定错误进行比较。*/
	UPROPERTY(BlueprintReadOnly)
	FString ErrorId;

	/** Error text to display to the user. */
	/** 显示给用户的错误信息文本。*/
	UPROPERTY(BlueprintReadOnly)
	FText ErrorText;

	/**
	 * Initialize this from an FOnlineErrorType
	 * @param InOnlineError the online error to initialize from
	 */
	/**
	 * 从 FOnlineErrorType 中初始化此值
	 * @参数 InOnlineError 用于初始化的在线错误信息
	 * 
	 */
	void COMMONUSER_API FromOnlineError(const FOnlineErrorType& InOnlineError);
};
